[2017-11-22 14:18:53] console.ERROR: Error thrown while running command "doctrine:generate:entity". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:generate:entity","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-22 14:18:53] console.DEBUG: Command "doctrine:generate:entity" exited with code "1" {"command":"doctrine:generate:entity","code":1} []
[2017-11-22 14:19:28] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8001 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/wilder10/PhpstormProjects/flyAround/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"/home/wilder10/PhpstormProjects/flyAround/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-22 14:19:47] console.ERROR: Error thrown while running command "doctrine:generate:entity". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:generate:entity","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-22 14:19:47] console.DEBUG: Command "doctrine:generate:entity" exited with code "1" {"command":"doctrine:generate:entity","code":1} []
[2017-11-22 14:21:21] console.ERROR: Error thrown while running command "doctrine:generate:entity". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:generate:entity","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-22 14:21:21] console.DEBUG: Command "doctrine:generate:entity" exited with code "1" {"command":"doctrine:generate:entity","code":1} []
[2017-11-22 14:22:44] console.ERROR: Error thrown while running command "doctrine:generate:entity". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:generate:entity","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-22 14:22:44] console.DEBUG: Command "doctrine:generate:entity" exited with code "1" {"command":"doctrine:generate:entity","code":1} []
[2017-11-22 14:23:57] console.ERROR: Error thrown while running command "doctrine:generate:entity". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:generate:entity","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-22 14:23:57] console.DEBUG: Command "doctrine:generate:entity" exited with code "1" {"command":"doctrine:generate:entity","code":1} []
[2017-11-22 14:24:46] console.DEBUG: Command "server:start" exited with code "1" {"command":"server:start","code":1} []
[2017-11-22 14:25:03] console.ERROR: Error thrown while running command "doctrine:generate:entity". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:generate:entity","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-22 14:25:03] console.DEBUG: Command "doctrine:generate:entity" exited with code "1" {"command":"doctrine:generate:entity","code":1} []
[2017-11-22 14:26:16] console.ERROR: Error thrown while running command "doctrine:generate:entity". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/wilder10/PhpstormProjects/flyAround/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:generate:entity","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-22 14:26:16] console.DEBUG: Command "doctrine:generate:entity" exited with code "1" {"command":"doctrine:generate:entity","code":1} []
[2017-11-22 14:58:57] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2017-11-22 14:59:08] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2017-11-22 14:59:08] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2017-11-22 14:59:08] doctrine.DEBUG: CREATE TABLE flight (id INT AUTO_INCREMENT NOT NULL, departure VARCHAR(32) NOT NULL, arrival VARCHAR(32) NOT NULL, nbFreeSeats SMALLINT NOT NULL, seatPrice DOUBLE PRECISION NOT NULL, takeOffTime DATETIME NOT NULL, publicationDate DATETIME NOT NULL, description LONGTEXT NOT NULL, pilot VARCHAR(32) NOT NULL, plane VARCHAR(64) NOT NULL, wasDone TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-22 14:59:08] doctrine.DEBUG: CREATE TABLE plane_model (id INT AUTO_INCREMENT NOT NULL, model VARCHAR(128) NOT NULL, manufacturer VARCHAR(64) NOT NULL, cruiseSpeed SMALLINT NOT NULL, planeNbSeats SMALLINT NOT NULL, isAvailable TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-22 14:59:08] doctrine.DEBUG: CREATE TABLE terrain (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(128) NOT NULL, icao VARCHAR(4) NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, adress VARCHAR(128) NOT NULL, city VARCHAR(128) NOT NULL, zipcode VARCHAR(128) NOT NULL, country VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-22 14:59:08] doctrine.DEBUG: CREATE TABLE reservation (id INT AUTO_INCREMENT NOT NULL, nbReservedSeats SMALLINT NOT NULL, publicationDate DATETIME NOT NULL, passenger VARCHAR(32) NOT NULL, flight VARCHAR(32) NOT NULL, wasDone TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-22 16:00:27] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8001 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/wilder10/PhpstormProjects/flyAround/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"/home/wilder10/PhpstormProjects/flyAround/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-22 16:01:15] request.INFO: Matched route "planemodel_index". {"route":"planemodel_index","route_parameters":{"_controller":"AppBundle\\Controller\\PlaneModelController::indexAction","_route":"planemodel_index"},"request_uri":"http://localhost:8001/planemodel/","method":"GET"} []
[2017-11-22 16:01:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-11-22 16:01:15] doctrine.DEBUG: SELECT t0.id AS id_1, t0.model AS model_2, t0.manufacturer AS manufacturer_3, t0.cruiseSpeed AS cruiseSpeed_4, t0.planeNbSeats AS planeNbSeats_5, t0.isAvailable AS isAvailable_6 FROM plane_model t0 [] []
[2017-11-22 16:01:15] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"51dfd6","_route":"_wdt"},"request_uri":"http://localhost:8001/_wdt/51dfd6","method":"GET"} []
[2017-11-22 16:17:04] console.DEBUG: Command "server:stop" exited with code "1" {"command":"server:stop","code":1} []
